/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/folders": {
    /** Retrieve a list of folders */
    get: {
      parameters: {
        query: {
          parent?: string;
        };
      };
      responses: {
        /** The list of folders */
        200: {
          content: {
            "application/json": components["schemas"]["Folder"][];
          };
        };
        400: components["responses"]["400"];
      };
    };
    /** Create a new folder */
    post: {
      responses: {
        /** Created folder */
        201: {
          content: {
            "application/json": components["schemas"]["Folder"];
          };
        };
        422: components["responses"]["validationError"];
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            parent?: (string | null) | (number | null);
          };
        };
      };
    };
  };
  "/folders/{id}": {
    /** Delete a folder */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** FolderResource cannot be deleted */
        403: unknown;
        /** FolderResource not found */
        404: unknown;
      };
    };
  };
  "/files": {
    /** Retrieve a list of files */
    get: {
      parameters: {
        query: {
          folder?: string;
        };
      };
      responses: {
        /** The list of files */
        200: {
          content: {
            "application/json": components["schemas"]["File"][];
          };
        };
        400: components["responses"]["400"];
        422: components["responses"]["validationError"];
      };
    };
    /** Upload a new file */
    post: {
      responses: {
        /** Uploaded file */
        201: {
          content: {
            "application/json": components["schemas"]["File"];
          };
        };
      };
      requestBody: {
        content: {
          "multipart/form-data": {
            /** Format: binary */
            file: string;
            folder: string | number;
          };
        };
      };
    };
  };
  "/files/{id}": {
    /** Delete a file */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** File not found */
        404: unknown;
      };
    };
  };
}

export interface components {
  schemas: {
    Folder: {
      id: components["schemas"]["ID"];
      /** @description FolderResource name */
      name: string;
      parent?: components["schemas"]["NullableID"];
    };
    File: {
      id: components["schemas"]["ID"];
      /** @description FolderResource name */
      name: string;
      /** @description Public url */
      url: string;
      /** @description File size */
      size?: number;
      folder?: components["schemas"]["NullableID"];
      thumbnail: string;
    };
    ID: string | number;
    NullableID: (string | null) | (number | null);
  };
  responses: {
    /** Bad request */
    400: {
      content: {
        "application/json": unknown;
      };
    };
    /** ValidationError */
    validationError: {
      content: {
        "application/json": {
          message?: string;
          errors?: { [key: string]: string[] };
        };
      };
    };
  };
}

export interface operations {}

export interface external {}
